package com.amk2.musicrunner.utilities;

import com.amk2.musicrunner.musiclist.PlaylistMetaData;

import java.util.ArrayList;

/**
 * Created by daz on 11/9/14.
 */
public interface OnPlaylistCreatedListener {
    void OnPlaylistCreated (ArrayList<Object> autoGeneratedPlaylistMetaDataHashMap);
}
